import { BookMarkedIcon, SquareLibraryIcon } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Book & Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto flex h-screen flex-col justify-center">
          <header className="flex justify-between border-b-1">
            <Link
              href="/"
              className="flex items-center text-3xl font-semibold tracking-tight text-green-500"
            >
              <BookMarkedIcon size={28} /> BookMark
            </Link>
            <div className="flex items-center gap-5">
              <Link
                href="/bookcase"
                className="hover: rounded-full border border-blue-300 p-1 ring-1 transition-all hover:ring-blue-500 active:scale-75"
              >
                <SquareLibraryIcon />
              </Link>
              <Link href="/my" className="">
                My
              </Link>
              <Link href="/sign">Sign</Link>
            </div>
          </header>
          <main className="flex-1">{children}</main>
          <footer className="text-center text-green-500">
            &#169; 김승구 @2025
          </footer>
        </div>
      </body>
    </html>
  );
}
